### ISSUE TITLE
phpSysInfo requires the simplexml extension

### ISSUE THREAD

**Issue by DeMiro5001** [YunoHost-Apps/phpsysinfo_ynh#22]
Vps (ovh) with a fresh install of yunohost. Apps installed : nextcloud, mattermost add phpsysinfo (all latest version).
Phpsysinfo shows only this message : 
`phpSysInfo requires the simplexml extension to php in order to work properly.`
Diagnosis https://paste.yunohost.org/raw/liledafota

**Comment by Satadaes** [comment]
same issue

**Comment by inrepublica** [comment]
Effectivement je rencontre la même erreur... pourtant le package simpleXML est bien installé...

**Comment by inrepublica** [comment]
Solve by #27
