### ISSUE TITLE
PSIAndroid ?

### ISSUE THREAD

**Issue by Thatoo** [YunoHost-Apps/phpsysinfo_ynh#8]
Hello,

Would it be possible to make this yunohost app compatible with PSIAndroid ?
https://f-droid.org/fr/packages/com.phpsysinfo/
If it is possible to do so without making the yunohost app public, that would be really great.

**Comment by inrepublica** [comment]
For me it works great. Just setup public access when you install phpsysinfo in yunohost.

**Comment by Thatoo** [comment]
OK but it means that all information are publicly available also... 
In PSIAndroid, I saw that it's possible to log in with id/password. Would it be possible to set that on 
phpsysinfo_ynh ?

**Comment by inrepublica** [comment]
Ok apparently, access can be restricted using an .htaccess -> http://arobaseinformatique.eklablog.com/monitorer-son-systeme-avec-phpsysinfo-a105205574

Yunohost don't use Apache but Nginx for the webserver. I don't know if it's possible :-(

**Comment by Thatoo** [comment]
If I understand well this page : https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/ ,
in the install script, we need
```
sudo apt install httpd-tools
sudo htpasswd -c /home/$USERNAME/.htpass_phpsysinfo $USERNAME  #$USERNAME being the user name of the admin of the app
```
it will ask for password
and then we need to add
```
    auth_basic           “Administrator’s Area”;
    auth_basic_user_file /home/$USERNAME/.htpass_phpsysinfo; 

```
to the 
`location __PATH__/ {`
of nginx

**Comment by Thatoo** [comment]
I'm offering this idea but I'm not 100% sure : https://github.com/YunoHost-Apps/phpsysinfo_ynh/pull/9

**Comment by inrepublica** [comment]
If i do this, private access with SSO is broken... Another problem is to put the password without console access :-(

**Comment by inrepublica** [comment]
I left a message on the official forum for help. -> https://forum.yunohost.org/t/phpsysinfo-securiser-lacces-via-http-basic-authentication/12721

**Comment by inrepublica** [comment]
Not possible to work with yunohost sso.
